services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: axum_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "16787:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d axum_server"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
