[build]
assets = [
  "public",
  "uploads",
  "templates",         # incluye los archivos dentro de public
]

[secrets]
DATABASE_URL="postgres://postgres:postgres@localhost:16787/axum_server"
SECRET_KEY_JWT="sdadakj_19234ÑpoM14I83_.,@?¿98"